---
title: "GLOE-seq analysis reads under pileup"
output: html_notebook
---

```{r message=FALSE}

library(ggplot2)
library(reshape2)
library(dplyr)
library(ggpubr)
library(elsasserlib)

source('../lib/lib_embed_data.v1.0.R')

```

```{r}
df <- read.delim("../data/pileup-analysis/pileup_fractions.txt",header = F)
colnames(df) <- c("condition","total","fltd","pileup")
df$frac <- df$pileup/df$fltd * 100

comp <- list(c("WT UT","WT 24hr"), c("WT 24hr", "KO 24hr"))

compare_means(frac ~ condition, data = df,method = "t.test",p.adjust.method = "bonferroni", paired = F)
```

```{r fig.width = 5, fig.height = 5}
ggbarplot(df,x = "condition", y="frac", add=c("mean_se", "jitter")) + stat_compare_means(comparisons = comp,method = "t.test",bracket.size = ) +
theme_elsasserlab_print()

embed_last_plot("frac_under_pile")
```
```{r}
stats <- read.delim("../data/pileup-analysis/pileup_stats.txt",header = T)

stats$unique <- stats$plus_peaks_unique + stats$minus_peaks_unique
stats$shared <- stats$plus_peaks_downsampled + stats$minus_peaks_downsampled - stats$unique

mdf <- melt(stats[c(3,6),c(1,10,11)])

ggbarplot(mdf,x = "condition", y="value",label = mdf$variable)
embed_last_plot("stats_piles")

```


